data_config:
  root: ./data/bail
  transform: normalize

model_config: 
  hidden_dim: 32
  dropout: 0.5
  gc_layer: 2
  bn: false
  weight_decay: 1.0e-5
  lr: 1.0e-2
  lr_scheduler: null
  lr_decay_steps: 20
  lr_decay_rate: 0.1
  lr_decay_min_lr: 1.0e-5

retrain_config:
  tepoch: 10
  dist_mode: cosine
  indices_num: 3
  lr: 1.0e-4
  weight_decay: 1.0e-5
  epochs: 100
  causal_coeff: 1
  disentangle_coeff: 0.5
  rec_coeff: 0.5

epochs: 100