data_config:
  root: ./data/credit
  transform: null

model_config:
  hidden_dim: 16
  dropout: 0.5
  gc_layer: 1
  bn: false
  weight_decay: 1.0e-5
  lr: 2.0e-3
  lr_scheduler: null
  lr_decay_steps: 20
  lr_decay_rate: 0.1
  lr_decay_min_lr: 1.0e-5

epochs: 500
  